# Generated by Django 6.0.5 on 2026-06-04 00:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_peso_caja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('shift1', 'Turno 1'), ('shift2', 'Turno 2'), ('shift3', 'Turno 3'), ('shift4', 'Turno 4')], max_length=20)),
                ('machine', models.CharField(choices=[('STICKPACK', 'STICKPACK'), ('MULTIPACK1', 'MULTIPACK1'), ('MULTIPACK2', 'MULTIPACK2'), ('MESPACK', 'MESPACK '), ('FLEXPACK0', 'FLEXPACK0'), ('FLEXPACK1', 'FLEXPACK1'), ('FLEXPACK2', 'FLEXPACK2'), ('FLEXPACK3', 'FLEXPACK3'), ('VOLPACK', 'VOLPACK')], max_length=200)),
                ('state', models.CharField(choices=[('operativa', 'Operativa'), ('mantenimiento', 'Mantenimiento'), ('reparacion', 'Reparación'), ('parada', 'Parada')], max_length=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('dockworker_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dockworker_reports', to='reporte_peso_caja.employee')),
                ('operator_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte_peso_caja.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.PositiveIntegerField(default=0)),
                ('package', models.PositiveIntegerField(default=0)),
                ('package_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('produccion', 'Producción'), ('pausa', 'Pausa'), ('mantenimiento', 'Mantenimiento'), ('falla', 'Falla')], default='produccion', max_length=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='reporte_peso_caja.report')),
            ],
        ),
    ]
