# Generated by Django 6.0.5 on 2026-06-04 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_peso_caja', '0002_remove_employee_address_remove_employee_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdetail',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporte_peso_caja.employee'),
        ),
    ]
