# Generated by Django 6.0.5 on 2026-06-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_peso_caja', '0003_reportdetail_registered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='dockworker_code',
        ),
        migrations.AddField(
            model_name='report',
            name='presentation',
            field=models.CharField(choices=[('Cafe oro 15', 'Cafe oro 15'), ('Cafe oro 20', 'Cafe oro 20'), ('Cafe oro 45', 'Cafe oro 45'), ('Cafe oro 50', 'Cafe oro 50')], default='sin presentacion', max_length=200),
            preserve_default=False,
        ),
    ]
