# Generated by Django 6.0.5 on 2026-06-04 18:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_peso_caja', '0004_remove_report_dockworker_code_report_presentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdetail',
            name='package',
        ),
        migrations.RemoveField(
            model_name='reportdetail',
            name='package_weight',
        ),
        migrations.RemoveField(
            model_name='reportdetail',
            name='total_weight',
        ),
        migrations.AddField(
            model_name='reportdetail',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
