# Generated by Django 6.0.5 on 2026-06-04 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_peso_caja', '0005_remove_reportdetail_package_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reportdetail',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='reportdetail',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='reportdetail',
            name='box',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reportdetail',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportdetail',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportdetail',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte_peso_caja.report'),
        ),
        migrations.AlterField(
            model_name='reportdetail',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reportdetail',
            name='status',
            field=models.CharField(choices=[('produccion', 'Producción'), ('pausa', 'Pausa'), ('terminado', 'Terminado')], default='produccion', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportdetail',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
