# Generated by Django 6.0.5 on 2026-06-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_peso_caja', '0006_remove_reportdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdetail',
            name='box',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
